### ISSUE TITLE
heros.json and Hero_Role_Data_Uptodate.csv

### ISSUE THREAD

**Issue by kroonhorstdino** [adam-katona/dota2_death_prediction#1]
In preprocess.py the files heros.json and Hero_Role_Data_Uptodate.csv are referenced:
`
    #JSON_PATH = '/users/ak1774/scratch/esport/death_prediction/heros.json'
    #HERO_ROLE_CSV_PATH = "/users/ak1774/scratch/esport/death_prediction/Hero_Role_Data_Uptodate.csv"`

However, I wasn't able to find these files in the repository.
Are these files accessible anywhere or do they have to be generated somehow?

**Comment by adam-katona** [comment]
Those never really worked, commented out the call in preprocess.py
